### ISSUE TITLE
Doesn't work on Firefox 42

### ISSUE THREAD

**Issue by drvink** [piroor/xulmigemo#15]
This is a really wonderful extension--will it ever be updated to work with newer versions of Firefox?

**Comment by piroor** [comment]
Now XUL/Migemo 0.14.x is available, and only Firefox 45 and later are supported.

**Comment by drvink** [comment]
This is great to hear! Thank you! I'll try it out.

**Comment by drvink** [comment]
Thanks again so much for updating this extension--it works great!
