### ISSUE TITLE
Inconsistency on some pages

### ISSUE THREAD

**Issue by pintassilgo** [piroor/xulmigemo#18]
Example:

Search "brazil" in the following page:
http://www.rsssf.com/sacups/copabalance.html

The first occurrence is highlighted, but not focused. If you press F3 (next), nothing happens. If you press Shift+F3 (previous), the last occurence is highlighted but again not focused. Then Shift+F3 no longer work, just one time F3, returning to first occurrence. But in reality there are six "brazil" results.

Switch to Normal Find to see desired behavior.

**Comment by piroor** [comment]
Thanks! By recent commits this problem seems to be fixed for me.

**Comment by pintassilgo** [comment]
Confirmed, now it's working properly. Thanks!
