### ISSUE TITLE
Shutdown crash Nightly49.0a1(2016-May-28) + XUL/Migemo0.14.4.2016052800a182536

### ISSUE THREAD

**Issue by alice0775** [piroor/xulmigemo#22]
Browser crashes when exit.

Reproducible: always

Steps to reproduce:
1. Start Nightly49.0a1(2016-May-28) with new profile
    and set xpinstall.signatures.required = false
2. Open http://piro.sakura.ne.jp/xul/xpi/nightly/
    and Install nightly 0.14.4.2016052800a182536
3. Configure Japanese dic
4. Restart browser
5. Ctrl+H to open history sidebar
    and type "index" without quotation marks
6. Quit browser

Actual Results:
Crash bp-7ae71e15-d2e8-4c4e-8c5c-8d2b82160529

**Comment by alice0775** [comment]
Crash Report  link : https://crash-stats.mozilla.com/report/index/7ae71e15-d2e8-4c4e-8c5c-8d2b82160529

**Comment by piroor** [comment]
Thanks, but I couldn't reproduce the problem on my environment. Does the commit b57d0a5cb729bee99cdfd76b852106b78591489a fix this issue?

**Comment by alice0775** [comment]
Tested with latest XUL/Migemo 0.14.4.2016052900a183017 (latst nightly build ),
I am not able to reproduce the crash.

Thanks.

**Comment by piroor** [comment]
Thank you for a verification!
